// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.0
// source: proto/pbs2/a.proto

package pbs2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ServerStreamReq) Reset() {
	*x = ServerStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pbs2_a_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamReq) ProtoMessage() {}

func (x *ServerStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbs2_a_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamReq.ProtoReflect.Descriptor instead.
func (*ServerStreamReq) Descriptor() ([]byte, []int) {
	return file_proto_pbs2_a_proto_rawDescGZIP(), []int{0}
}

func (x *ServerStreamReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ServerStreamRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ServerStreamRes) Reset() {
	*x = ServerStreamRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pbs2_a_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamRes) ProtoMessage() {}

func (x *ServerStreamRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbs2_a_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamRes.ProtoReflect.Descriptor instead.
func (*ServerStreamRes) Descriptor() ([]byte, []int) {
	return file_proto_pbs2_a_proto_rawDescGZIP(), []int{1}
}

func (x *ServerStreamRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ClientStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ClientStreamReq) Reset() {
	*x = ClientStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pbs2_a_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamReq) ProtoMessage() {}

func (x *ClientStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbs2_a_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamReq.ProtoReflect.Descriptor instead.
func (*ClientStreamReq) Descriptor() ([]byte, []int) {
	return file_proto_pbs2_a_proto_rawDescGZIP(), []int{2}
}

func (x *ClientStreamReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ClientStreamRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ClientStreamRes) Reset() {
	*x = ClientStreamRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pbs2_a_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamRes) ProtoMessage() {}

func (x *ClientStreamRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbs2_a_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamRes.ProtoReflect.Descriptor instead.
func (*ClientStreamRes) Descriptor() ([]byte, []int) {
	return file_proto_pbs2_a_proto_rawDescGZIP(), []int{3}
}

func (x *ClientStreamRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TwoWayStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TwoWayStreamReq) Reset() {
	*x = TwoWayStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pbs2_a_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwoWayStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoWayStreamReq) ProtoMessage() {}

func (x *TwoWayStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbs2_a_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoWayStreamReq.ProtoReflect.Descriptor instead.
func (*TwoWayStreamReq) Descriptor() ([]byte, []int) {
	return file_proto_pbs2_a_proto_rawDescGZIP(), []int{4}
}

func (x *TwoWayStreamReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TwoWayStreamRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TwoWayStreamRes) Reset() {
	*x = TwoWayStreamRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pbs2_a_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwoWayStreamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoWayStreamRes) ProtoMessage() {}

func (x *TwoWayStreamRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pbs2_a_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoWayStreamRes.ProtoReflect.Descriptor instead.
func (*TwoWayStreamRes) Descriptor() ([]byte, []int) {
	return file_proto_pbs2_a_proto_rawDescGZIP(), []int{5}
}

func (x *TwoWayStreamRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_pbs2_a_proto protoreflect.FileDescriptor

var file_proto_pbs2_a_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x73, 0x32, 0x2f, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x23, 0x0a, 0x0f, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x23,
	0x0a, 0x0f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x23, 0x0a, 0x0f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x23, 0x0a, 0x0f, 0x54, 0x77, 0x6f, 0x57,
	0x61, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x23, 0x0a,
	0x0f, 0x54, 0x77, 0x6f, 0x57, 0x61, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0xae, 0x01, 0x0a, 0x02, 0x53, 0x32, 0x12, 0x36, 0x0a, 0x0c, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x10, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x36, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x10, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x12, 0x38, 0x0a, 0x0c, 0x54, 0x77, 0x6f,
	0x57, 0x61, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x10, 0x2e, 0x54, 0x77, 0x6f, 0x57,
	0x61, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x54, 0x77,
	0x6f, 0x57, 0x61, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x70, 0x62, 0x73, 0x32, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pbs2_a_proto_rawDescOnce sync.Once
	file_proto_pbs2_a_proto_rawDescData = file_proto_pbs2_a_proto_rawDesc
)

func file_proto_pbs2_a_proto_rawDescGZIP() []byte {
	file_proto_pbs2_a_proto_rawDescOnce.Do(func() {
		file_proto_pbs2_a_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pbs2_a_proto_rawDescData)
	})
	return file_proto_pbs2_a_proto_rawDescData
}

var file_proto_pbs2_a_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_pbs2_a_proto_goTypes = []interface{}{
	(*ServerStreamReq)(nil), // 0: ServerStreamReq
	(*ServerStreamRes)(nil), // 1: ServerStreamRes
	(*ClientStreamReq)(nil), // 2: ClientStreamReq
	(*ClientStreamRes)(nil), // 3: ClientStreamRes
	(*TwoWayStreamReq)(nil), // 4: TwoWayStreamReq
	(*TwoWayStreamRes)(nil), // 5: TwoWayStreamRes
}
var file_proto_pbs2_a_proto_depIdxs = []int32{
	0, // 0: S2.ServerStream:input_type -> ServerStreamReq
	2, // 1: S2.ClientStream:input_type -> ClientStreamReq
	4, // 2: S2.TwoWayStream:input_type -> TwoWayStreamReq
	1, // 3: S2.ServerStream:output_type -> ServerStreamRes
	3, // 4: S2.ClientStream:output_type -> ClientStreamRes
	5, // 5: S2.TwoWayStream:output_type -> TwoWayStreamRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pbs2_a_proto_init() }
func file_proto_pbs2_a_proto_init() {
	if File_proto_pbs2_a_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pbs2_a_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pbs2_a_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pbs2_a_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pbs2_a_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pbs2_a_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwoWayStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pbs2_a_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TwoWayStreamRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pbs2_a_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pbs2_a_proto_goTypes,
		DependencyIndexes: file_proto_pbs2_a_proto_depIdxs,
		MessageInfos:      file_proto_pbs2_a_proto_msgTypes,
	}.Build()
	File_proto_pbs2_a_proto = out.File
	file_proto_pbs2_a_proto_rawDesc = nil
	file_proto_pbs2_a_proto_goTypes = nil
	file_proto_pbs2_a_proto_depIdxs = nil
}
