version: '3.3'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    privileged: true
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    command:
      - --requirepass "Tht940415,./"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=Tht940415,./
    command:
      - --character-set-server=utf8mb4

  elasticsearch:
    image: elasticsearch:8.2.3
    container_name: elasticsearch
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    ports:
      - 9200:9200
      - 9300:9300
    privileged: true

  # kibana:
  #   image: kibana:7.5.2
  #   container_name: kibana
  #   restart: always
  #   privileged: true
  #   environment:
  #     - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
  #     - SERVER_HOST=0.0.0.0
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5601:5601

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    privileged: true
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    privileged: true
    ports:
      - 3000:3000
